#%RAML 1.0 NamedExample
{
  "cpf": "11122233345",
  "cnpj": "11222333000102",
  "canal": "bot",
  "menu": "empresa",
  "descricao": "Cliente desligou antes de responder as perguntas de confirmação",
  "dataHora": "2018-11-21T10:00:00-03:00",
  "callId": 12345
}